language: java
os: osx
addons:
  chrome: stable
jdk: oraclejdk8
script:
  - "google-chrome --version"
  - ./gradlew clean build
before_script:
  - sleep 15
  - echo "Before install - OS is $TRAVIS_OS_NAME"
    echo "Updating both homebrew, mongodb and redis-server"
    if [[ $TRAVIS_OS_NAME = 'osx' ]]; then
    echo "Updating homebrew"
    brew update
    echo "Installing and starting mongodb"
    brew install mongodb
    # create a folder for mongodb to prevent an error on mac osx
    sudo mkdir -p /data/db
    brew services start mongodb
    echo "Installing and starting redis-server"
    brew install redis
    brew services start redis
    fi


services:
  - mongodb
notifications:
  email: false