language: java
os: osx
addons:
  chrome: stable
jdk: oraclejdk8
script:
  - "google-chrome --version"
  - ./gradlew clean build
before_script:
  - brew update
  - brew install mongodb
  - brew services start mongodb

services:
  - mongodb
notifications:
  email: false