addons:
  chrome: stable
before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
language: java
jdk: oraclejdk8
script:
  ./gradlew clean build
services:
  - mongodb
notifications:
  email: false